# Stage 1: Build
FROM node:20-alpine AS builder

WORKDIR /app/frontend

# Copiar solo el frontend
COPY frontend/package*.json ./
COPY frontend/ ./

RUN npm install
RUN npm run build

# Stage 2: Nginx
FROM nginx:stable-alpine

COPY --from=builder /app/frontend/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
