FROM node:20-alpine

WORKDIR /app

# Instalar dependencias necesarias para Prisma y node-gyp si fuera necesario
RUN apk add --no-cache openssl libc6-compat

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código (aunque se montará un volumen en dev)
COPY . .

# Generar cliente Prisma
RUN npx prisma generate

EXPOSE 3000

CMD ["npm", "run", "dev"]
