services:
  backend:
    image: "${DOCKER_IMAGE_BACKEND:-campus-virtual-backend:latest}"
    container_name: campus_virtual_backend
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: production
      PORT: 3100
    ports:
      - "3100:3100"
    networks:
      - campus_network

  frontend:
    image: "${DOCKER_IMAGE_FRONTEND:-campus-virtual-frontend:latest}"
    container_name: campus_virtual_frontend
    restart: always
    ports:
      - "8080:80"
    networks:
      - campus_network

networks:
  campus_network:
    driver: bridge
